const questions = [
  // SILLY
  { text: "Would you rather have to narrate everything you do out loud like a nature documentary, or only be able to communicate via interpretive dance?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather have hiccups every time you tell a lie, or sneeze every time someone nearby is attracted to you?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather only be able to eat foods that are one single color for the rest of your life — or only be able to eat foods that are perfectly circular?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather have to wear a cape everywhere for a year, or only be able to speak in questions?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather your laugh be replaced with a full foghorn blast, or your sneezes sound like a tiny sad trombone?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather have to high-five everyone you make eye contact with, or narrate your dreams to a stranger every morning?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather swap bodies with your pet for a week, or swap bodies with your most boring coworker?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather only be able to shop for groceries at a gas station, or only eat meals served in a stadium cup?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather have a tail you can't control that wags when you're excited, or ears that flatten when you're nervous?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather fight 100 duck-sized horses or one horse-sized duck — but you have to explain your strategy first?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather have to moonwalk everywhere you go for a year, or only be able to enter rooms by doing a dramatic slow-motion entrance?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather your phone autocorrect everything to pirate speak, or have your GPS give directions exclusively in motivational quotes?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather every photo taken of you comes out looking like a Renaissance painting, or a low-budget 1990s yearbook photo?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather narrate your own life in a British nature documentary voice, or have Morgan Freeman narrate only your most mundane moments?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather sneeze glitter every time, or have a tiny crowd cheer for you every time you parallel park?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather wake up every morning with a different accent you can't control, or a different catchphrase you have to say at least once per day?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather your laugh be replaced with the sound of a dial-up modem connecting, or a very enthusiastic seal?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather every email you send ends with 'Sent from my spaceship,' or every voicemail starts with a four-second kazoo intro?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather have to wear a sash that says your current mood at all times, or a name tag with what you're actually thinking?", vibe: "silly", category: "Would You Rather" },
  { text: "Would you rather your shopping cart always has one squeaky wheel you can't fix, or the self-checkout machine flags every single item you scan?", vibe: "silly", category: "Would You Rather" },

  { text: "You've been elected mayor of a city where everything is the wrong size. What's your first executive order?", vibe: "silly", category: "Absurd Hypotheticals" },
  { text: "A wizard gives you the ability to speak to one inanimate object in our home. Which one do you choose and what do you think it would say about us?", vibe: "silly", category: "Absurd Hypotheticals" },
  { text: "You wake up and you have the powers of the most useless superhero imaginable. What's your power and what do you do with your day?", vibe: "silly", category: "Absurd Hypotheticals" },
  { text: "You're a villain in a movie. What is your unnecessarily complicated evil plan, and what's your aesthetic?", vibe: "silly", category: "Absurd Hypotheticals" },
  { text: "A time traveler from 1,000 years in the future shows up and says our home is a famous historical site. What do they think happened here?", vibe: "silly", category: "Absurd Hypotheticals" },
  { text: "You're dropped into a reality show you are completely unqualified for. Which show, and how long do you last?", vibe: "silly", category: "Absurd Hypotheticals" },
  { text: "Scientists discover that a random animal has been watching and judging humans for centuries. Which animal do you think it is, and what would their critique be?", vibe: "silly", category: "Absurd Hypotheticals" },
  { text: "You have to open a restaurant, but the theme can only be described as 'chaotic.' What's the concept, the menu, the vibe?", vibe: "silly", category: "Absurd Hypotheticals" },
  { text: "You have $1,000 and exactly one hour to spend it on the most unhinged thing possible. What do you buy?", vibe: "silly", category: "Absurd Hypotheticals" },
  { text: "A documentary crew follows us for a week and titles it after what they observe. What's the documentary called?", vibe: "silly", category: "Absurd Hypotheticals" },

  { text: "What's a completely unhinged food opinion you've never admitted out loud?", vibe: "silly", category: "Hot Takes" },
  { text: "What's a movie or show everyone loves that you think is secretly terrible?", vibe: "silly", category: "Hot Takes" },
  { text: "What's a common social ritual that you think is secretly pointless but you participate in anyway?", vibe: "silly", category: "Hot Takes" },
  { text: "What's a hill you would absolutely die on, no matter how ridiculous it sounds?", vibe: "silly", category: "Hot Takes" },
  { text: "What's something most people consider a treat that you could happily live without forever?", vibe: "silly", category: "Hot Takes" },
  { text: "What's a wildly overrated tourist attraction you think people only pretend to enjoy?", vibe: "silly", category: "Hot Takes" },
  { text: "What's a commonly praised personality trait that you actually find a little annoying?", vibe: "silly", category: "Hot Takes" },
  { text: "What's the most controversial thing you believe about how a household should be run?", vibe: "silly", category: "Hot Takes" },
  { text: "What's an animal that gets way more love than it deserves, and which underrated animal should replace it?", vibe: "silly", category: "Hot Takes" },
  { text: "What's a technology, app, or gadget that you think secretly makes life worse?", vibe: "silly", category: "Hot Takes" },

  { text: "What's the dumbest thing you've ever done that turned out totally fine, and you've never told anyone?", vibe: "silly", category: "Confessions" },
  { text: "What's a completely irrational fear you've kept quiet because you know it's embarrassing?", vibe: "silly", category: "Confessions" },
  { text: "What's the last thing you Googled that you'd be slightly embarrassed to explain to me?", vibe: "silly", category: "Confessions" },
  { text: "What's a habit or ritual you do when you're alone that would look absolutely unhinged to a stranger?", vibe: "silly", category: "Confessions" },
  { text: "What's something you've been lying about — even to yourself — for years?", vibe: "silly", category: "Confessions" },
  { text: "What's a phase you went through that you've quietly hoped I'd never find out about?", vibe: "silly", category: "Confessions" },
  { text: "What's something you'd be too embarrassed to ask a doctor but have just... been quietly wondering about?", vibe: "silly", category: "Confessions" },
  { text: "What's the most unhinged thing you've ever convinced yourself was a good idea at the time?", vibe: "silly", category: "Confessions" },
  { text: "What's a skill you've let people believe you have that you absolutely do not?", vibe: "silly", category: "Confessions" },
  { text: "What's the weirdest thing about yourself that you've actually grown kind of fond of?", vibe: "silly", category: "Confessions" },

  { text: "Unlimited soup forever or unlimited bread forever — you can only pick one, and the other ceases to exist?", vibe: "silly", category: "This or That" },
  { text: "You can only listen to one song for the rest of your life, or you can never hear music again — which?", vibe: "silly", category: "This or That" },
  { text: "Everyone can hear your thoughts for one day, or you can hear everyone else's thoughts for one hour?", vibe: "silly", category: "This or That" },
  { text: "Know the exact date of your death, or know the exact cause but not when?", vibe: "silly", category: "This or That" },
  { text: "Be permanently 10 minutes early to everything, or permanently 10 minutes late — and everyone knows it?", vibe: "silly", category: "This or That" },
  { text: "Have a rewind button for conversations, or a mute button for people around you?", vibe: "silly", category: "This or That" },
  { text: "Eat every meal in complete silence forever, or never eat alone again — even if you want to?", vibe: "silly", category: "This or That" },
  { text: "Have the ability to pause time but only for five seconds, or fast-forward time but only once?", vibe: "silly", category: "This or That" },
  { text: "Find out you're secretly famous in a country you've never visited, or discover a small fan account of yourself that's oddly accurate?", vibe: "silly", category: "This or That" },
  { text: "Live in a world with no mirrors ever, or a world where every reflective surface is slightly unflattering?", vibe: "silly", category: "This or That" },

  { text: "On a scale of 1–10, how likely am I to survive the first 24 hours of a zombie apocalypse? Justify your rating.", vibe: "silly", category: "Rate Each Other" },
  { text: "If our relationship was a restaurant, what would the Yelp reviews say? Read me one good one and one bad one.", vibe: "silly", category: "Rate Each Other" },
  { text: "What's my most chaotic personality trait, and how many stars out of five do you give it?", vibe: "silly", category: "Rate Each Other" },
  { text: "If you had to write my dating app bio — honest version — what would it say?", vibe: "silly", category: "Rate Each Other" },
  { text: "What animal would you say I most resemble in behavior, and why is it so accurate?", vibe: "silly", category: "Rate Each Other" },
  { text: "If I were a type of weather, what would I be, and is that a good thing?", vibe: "silly", category: "Rate Each Other" },
  { text: "What's my most questionable but endearing life choice, and how do you really feel about it?", vibe: "silly", category: "Rate Each Other" },
  { text: "What movie character am I most like — and is that a compliment?", vibe: "silly", category: "Rate Each Other" },
  { text: "If you had to describe how I load the dishwasher to a judge, what would your testimony be?", vibe: "silly", category: "Rate Each Other" },
  { text: "What's a thing I do that you find objectively ridiculous but have never actually said anything about?", vibe: "silly", category: "Rate Each Other" },

  { text: "What's the most unforgivable food combination you've ever eaten in secret and genuinely enjoyed?", vibe: "silly", category: "Unhinged Food Crimes" },
  { text: "You have to open a restaurant where every dish is named after a moment in our relationship. What's on the menu?", vibe: "silly", category: "Unhinged Food Crimes" },
  { text: "If our relationship were a flavor of ice cream, what would it be called and what's in it?", vibe: "silly", category: "Unhinged Food Crimes" },
  { text: "What food do you eat differently when no one is watching, and how differently are we talking?", vibe: "silly", category: "Unhinged Food Crimes" },
  { text: "You're on death row. Final meal — but it has to be embarrassing and specific. What is it?", vibe: "silly", category: "Unhinged Food Crimes" },
  { text: "If you had to eat one thing for every meal for a month straight and couldn't die from it, what would actually be kind of perfect?", vibe: "silly", category: "Unhinged Food Crimes" },
  { text: "What's the most unhinged thing you've eaten out of laziness that you'd describe as 'fine, actually'?", vibe: "silly", category: "Unhinged Food Crimes" },
  { text: "You discover a new food. It tastes incredible but looks disgusting and has a terrible name. Describe it.", vibe: "silly", category: "Unhinged Food Crimes" },
  { text: "What's a food you've been pretending to like for social reasons that you'd quietly eliminate from existence?", vibe: "silly", category: "Unhinged Food Crimes" },
  { text: "If someone wrote a tell-all book about your eating habits, what would the most shocking chapter reveal?", vibe: "silly", category: "Unhinged Food Crimes" },

  { text: "You wake up with one day of total immunity from consequences. What do you actually do?", vibe: "silly", category: "Chaos Energy" },
  { text: "What's the most chaotic but genuinely good idea you've had that nobody let you execute?", vibe: "silly", category: "Chaos Energy" },
  { text: "If you had to start a cult — for something completely harmless — what would it be devoted to?", vibe: "silly", category: "Chaos Energy" },
  { text: "What's a recurring thought you have that would make people question your sanity if you said it out loud?", vibe: "silly", category: "Chaos Energy" },
  { text: "If you could swap one mundane daily task with something completely absurd but equally effective, what would it be?", vibe: "silly", category: "Chaos Energy" },
  { text: "A news alert goes out about you. What does it say, and is it good or bad?", vibe: "silly", category: "Chaos Energy" },
  { text: "You're given full creative control of a theme park. What's the most unhinged ride you build first?", vibe: "silly", category: "Chaos Energy" },
  { text: "What's a completely unnecessary thing you are weirdly passionate about being right about?", vibe: "silly", category: "Chaos Energy" },
  { text: "If you had to sabotage someone's day in the pettiest, most harmless way imaginable, what would you do?", vibe: "silly", category: "Chaos Energy" },
  { text: "What's a hill you'd die on that, if you're honest, has no real stakes whatsoever?", vibe: "silly", category: "Chaos Energy" },

  { text: "What's something I do that makes absolutely no logical sense, and how have you made peace with it?", vibe: "silly", category: "Roast Your Partner" },
  { text: "If you had to describe my texting style to a jury, what would your opening statement be?", vibe: "silly", category: "Roast Your Partner" },
  { text: "What's a thing I genuinely believe about myself that you'd describe as... ambitious?", vibe: "silly", category: "Roast Your Partner" },
  { text: "What's the most 'very you' decision I've ever made — said with love, but also a little concern?", vibe: "silly", category: "Roast Your Partner" },
  { text: "If you had to describe how I act when I'm sick to a documentary crew, what would your interview say?", vibe: "silly", category: "Roast Your Partner" },
  { text: "What's an opinion I hold confidently that you secretly disagree with but let me have?", vibe: "silly", category: "Roast Your Partner" },
  { text: "What's the most unnecessary thing I've ever stressed about, and how did you handle staying quiet?", vibe: "silly", category: "Roast Your Partner" },
  { text: "What would the worst possible roommate review of me say — but written by someone who still liked me overall?", vibe: "silly", category: "Roast Your Partner" },
  { text: "What's a habit of mine that you have never mentioned but absolutely have an opinion about?", vibe: "silly", category: "Roast Your Partner" },
  { text: "If you pitched our relationship to a TV network, what genre would it be, and what's the logline?", vibe: "silly", category: "Roast Your Partner" },

  { text: "Describe the secret inner monologue I'm having right now, based purely on my face.", vibe: "silly", category: "Secret Life Of" },
  { text: "If our pets held a formal meeting about us while we slept, what would the agenda items be?", vibe: "silly", category: "Secret Life Of" },
  { text: "What do you think the people at our favorite restaurant actually say about us after we leave?", vibe: "silly", category: "Secret Life Of" },
  { text: "If you had to write a biography of my daily habits titled dramatically, what would it be called?", vibe: "silly", category: "Secret Life Of" },
  { text: "What do you think our neighbors genuinely believe about us based purely on what they can observe?", vibe: "silly", category: "Secret Life Of" },
  { text: "If our home had a Yelp page written by all the inanimate objects in it, what would the reviews say?", vibe: "silly", category: "Secret Life Of" },
  { text: "What do you think I'm like in a work meeting when you're not there? Give me the full impression.", vibe: "silly", category: "Secret Life Of" },
  { text: "If a stranger followed us around for a day and had to guess our jobs, hobbies, and deepest fears — what would they conclude?", vibe: "silly", category: "Secret Life Of" },
  { text: "What do you think our future kids will find most embarrassing about us?", vibe: "silly", category: "Secret Life Of" },
  { text: "If you had to describe what I'm like at 2am versus 2pm as two totally different characters, who are they?", vibe: "silly", category: "Secret Life Of" },

  { text: "What's a completely unsolicited and possibly unhinged take on something you've been sitting on for months?", vibe: "silly", category: "Unprompted Opinions" },
  { text: "What's a social norm that has always seemed fake to you that most people just go along with?", vibe: "silly", category: "Unprompted Opinions" },
  { text: "What's a thing that is universally considered classy that you secretly find a little pretentious?", vibe: "silly", category: "Unprompted Opinions" },
  { text: "What's a movie everyone insists is romantic that you think is actually kind of a red flag?", vibe: "silly", category: "Unprompted Opinions" },
  { text: "What's an unwritten rule of adulthood that you think is completely made up and nobody should have to follow?", vibe: "silly", category: "Unprompted Opinions" },
  { text: "What's something the internet collectively loves that you could go your whole life without hearing about again?", vibe: "silly", category: "Unprompted Opinions" },
  { text: "What's a piece of common advice people give that you think is actually terrible and backfires most of the time?", vibe: "silly", category: "Unprompted Opinions" },
  { text: "What's a thing that's considered a luxury that you think is completely overrated and not worth the money?", vibe: "silly", category: "Unprompted Opinions" },
  { text: "What's a word or phrase that has been so overused it has lost all meaning and you're tired of hearing it?", vibe: "silly", category: "Unprompted Opinions" },
  { text: "What's a trend from the last five years that you hope future generations just quietly agree to forget?", vibe: "silly", category: "Unprompted Opinions" },

  { text: "If we met ten years earlier than we did, do you think we'd have lasted — or would we have been a disaster?", vibe: "silly", category: "Alternate Universe Us" },
  { text: "If we had to live as a completely different kind of couple — different country, different era, different life — what version of us would actually thrive?", vibe: "silly", category: "Alternate Universe Us" },
  { text: "If we were roommates who didn't know we'd end up together, what would the moment of realization have been?", vibe: "silly", category: "Alternate Universe Us" },
  { text: "If our relationship had a theme song chosen by someone who only watched us for one afternoon, what would it be?", vibe: "silly", category: "Alternate Universe Us" },
  { text: "If we competed against each other on a game show, who would win, and would we still be married after?", vibe: "silly", category: "Alternate Universe Us" },
  { text: "If we had met on a terrible blind date set up by someone with bad judgment, at what point in the meal would you have started to come around?", vibe: "silly", category: "Alternate Universe Us" },
  { text: "If we were characters in a novel written about our life together, what genre would it be and what would the title be?", vibe: "silly", category: "Alternate Universe Us" },
  { text: "If we had to design a coat of arms for our household — like a formal family crest — what symbols and motto would it have?", vibe: "silly", category: "Alternate Universe Us" },
  { text: "If a time traveler from our future showed up tonight and gave us one piece of advice, what do you think it would be?", vibe: "silly", category: "Alternate Universe Us" },
  { text: "If we were forced to rebrand our relationship — new aesthetic, new vibe, new couple nickname — what's the pitch?", vibe: "silly", category: "Alternate Universe Us" },

  // DEEP
  { text: "What's a memory of us that you replay more than I'd probably guess?", vibe: "deep", category: "Memories" },
  { text: "Is there a version of me from early in our relationship you kind of miss?", vibe: "deep", category: "Memories" },
  { text: "What's the most surprised you've ever been by something I did?", vibe: "deep", category: "Memories" },
  { text: "What's a small, ordinary moment from our life together that you'd want to freeze in time?", vibe: "deep", category: "Memories" },
  { text: "Is there a trip, meal, or night out that was better than you expected going in?", vibe: "deep", category: "Memories" },
  { text: "What's something you said to me early on that you still think about?", vibe: "deep", category: "Memories" },
  { text: "What's a habit or quirk of mine that you've actually grown to love?", vibe: "deep", category: "Memories" },
  { text: "When did you first think 'this person really gets me'?", vibe: "deep", category: "Memories" },
  { text: "What's the hardest thing we've been through together that made us stronger?", vibe: "deep", category: "Memories" },
  { text: "Is there a joke or inside reference between us that never gets old for you?", vibe: "deep", category: "Memories" },

  { text: "If we could spend a full year anywhere in the world, with no work obligations, where and how would you want to live it?", vibe: "deep", category: "Dreams" },
  { text: "What's a version of our future life that you dream about but haven't really told me?", vibe: "deep", category: "Dreams" },
  { text: "If money and logistics didn't matter, what would your ideal Monday look like in ten years?", vibe: "deep", category: "Dreams" },
  { text: "Is there something you want us to try or build together that we haven't talked about seriously yet?", vibe: "deep", category: "Dreams" },
  { text: "What kind of old couple do you hope we become?", vibe: "deep", category: "Dreams" },
  { text: "What's one thing you want to do before we're 40 that we haven't done yet?", vibe: "deep", category: "Dreams" },
  { text: "If you could design our home from scratch anywhere, what would it look like and where would it be?", vibe: "deep", category: "Dreams" },
  { text: "What's a skill or hobby you'd love to develop together?", vibe: "deep", category: "Dreams" },
  { text: "If we could start a project, business, or creative thing together, what would it be?", vibe: "deep", category: "Dreams" },
  { text: "Is there something you want our relationship to look like in ten years that it doesn't quite look like yet?", vibe: "deep", category: "Dreams" },

  { text: "What's something you believe now that you didn't believe five years ago?", vibe: "deep", category: "Inner World" },
  { text: "What do you think I fundamentally misunderstand about you?", vibe: "deep", category: "Inner World" },
  { text: "What's a fear you've mostly kept to yourself?", vibe: "deep", category: "Inner World" },
  { text: "When do you feel most like yourself?", vibe: "deep", category: "Inner World" },
  { text: "What's something you're quietly proud of that you've never really said out loud?", vibe: "deep", category: "Inner World" },
  { text: "Is there a version of your life you didn't take that you still think about sometimes?", vibe: "deep", category: "Inner World" },
  { text: "What do you need more of right now that you haven't asked for?", vibe: "deep", category: "Inner World" },
  { text: "What's a value or belief that's become more important to you lately?", vibe: "deep", category: "Inner World" },
  { text: "When you're stressed, what does part of you wish I would just do without being asked?", vibe: "deep", category: "Inner World" },
  { text: "What's the question you're most afraid someone will ask you?", vibe: "deep", category: "Inner World" },

  { text: "What's something I do that makes you feel most loved that I probably don't realize?", vibe: "deep", category: "Us" },
  { text: "Is there a dynamic between us that you'd like to quietly shift?", vibe: "deep", category: "Us" },
  { text: "What's a conversation you've been avoiding having with me?", vibe: "deep", category: "Us" },
  { text: "What's something you wish we did more of together?", vibe: "deep", category: "Us" },
  { text: "How do you think we've changed each other?", vibe: "deep", category: "Us" },
  { text: "What do you think is our biggest strength as a couple?", vibe: "deep", category: "Us" },
  { text: "When do you feel most connected to me?", vibe: "deep", category: "Us" },
  { text: "What's something small I could do that would mean a lot to you right now?", vibe: "deep", category: "Us" },
  { text: "Is there a way I show up for you that surprised you — something you didn't expect from a partner?", vibe: "deep", category: "Us" },
  { text: "What's a thing I do that you brag about to your friends or family?", vibe: "deep", category: "Us" },

  { text: "If we had to live as a completely different type of couple — different city, different jobs, different lifestyle — what version of us would you choose?", vibe: "deep", category: "Hypotheticals" },
  { text: "If you could give us one superpower as a couple, what would it be?", vibe: "deep", category: "Hypotheticals" },
  { text: "If we were characters in a movie, what genre would it be and who would play us?", vibe: "deep", category: "Hypotheticals" },
  { text: "If you had to bet on the one thing most likely to make us laugh uncontrollably in the next year, what would it be?", vibe: "deep", category: "Hypotheticals" },
  { text: "If we could invite any three people — dead or alive — to dinner tonight, who would you pick and why?", vibe: "deep", category: "Hypotheticals" },
  { text: "If you had to describe our relationship using only song titles, what would they be?", vibe: "deep", category: "Hypotheticals" },
  { text: "If we swapped roles for a week — jobs, responsibilities, everything — what do you think would surprise you most?", vibe: "deep", category: "Hypotheticals" },
  { text: "If we could relive one day of our relationship exactly as it was, which one would you pick?", vibe: "deep", category: "Hypotheticals" },
  { text: "If you had to design our perfect weekend from scratch, what would it include?", vibe: "deep", category: "Hypotheticals" },
  { text: "If we were forced to do a reality TV show together, which one would we survive?", vibe: "deep", category: "Hypotheticals" },

  { text: "What's something I've done recently that made you think 'yeah, I picked the right person'?", vibe: "deep", category: "Gratitude" },
  { text: "What's a way I've grown that you've admired but never really said?", vibe: "deep", category: "Gratitude" },
  { text: "What's one thing about our life together that you never want to take for granted?", vibe: "deep", category: "Gratitude" },
  { text: "Is there something I helped you through that you don't think I know the full impact of?", vibe: "deep", category: "Gratitude" },
  { text: "What's a quality in me that you hope rubs off on you more?", vibe: "deep", category: "Gratitude" },
  { text: "What's something about the way we live that makes you genuinely happy?", vibe: "deep", category: "Gratitude" },
  { text: "What's a moment in the past year where you felt really lucky to be with me?", vibe: "deep", category: "Gratitude" },
  { text: "Is there something I did during a hard time for you that stayed with you?", vibe: "deep", category: "Gratitude" },
  { text: "What's something we have that you'd never want to change?", vibe: "deep", category: "Gratitude" },
  { text: "If you had to write a one-sentence love letter to me right now, what would it say?", vibe: "deep", category: "Gratitude" },

  { text: "What's something you've started to understand about yourself only because of being with me?", vibe: "deep", category: "Late Night Honest" },
  { text: "What's a fear about us that you've already talked yourself out of but that still visits you sometimes?", vibe: "deep", category: "Late Night Honest" },
  { text: "What's something you've never asked me because you weren't sure you wanted the answer?", vibe: "deep", category: "Late Night Honest" },
  { text: "When do you feel most like yourself with me — like, when do you feel least like you have to try?", vibe: "deep", category: "Late Night Honest" },
  { text: "What's a thing you hope I never stop doing, that you'd miss deeply if it quietly disappeared?", vibe: "deep", category: "Late Night Honest" },
  { text: "What's something you've wanted to be for me that you're still working on becoming?", vibe: "deep", category: "Late Night Honest" },
  { text: "Is there something about this season of our life together that you're trying to really soak in before it changes?", vibe: "deep", category: "Late Night Honest" },
  { text: "What's a version of me you fell for that you hope has never fully grown up?", vibe: "deep", category: "Late Night Honest" },
  { text: "What's the kindest thing I've ever done for you that I might not even remember doing?", vibe: "deep", category: "Late Night Honest" },
  { text: "If you had to describe what loving me has taught you in one sentence, what would it be?", vibe: "deep", category: "Late Night Honest" },

  { text: "What's something about our relationship that you've never put into words but has been sitting in your chest?", vibe: "deep", category: "Unfiltered Honesty" },
  { text: "When's the last time I made you feel genuinely seen, and did I even know I was doing it?", vibe: "deep", category: "Unfiltered Honesty" },
  { text: "What's something you've forgiven me for that you never actually told me you forgave me for?", vibe: "deep", category: "Unfiltered Honesty" },
  { text: "What's a version of our future that scares you a little — not because it's bad, but because it matters?", vibe: "deep", category: "Unfiltered Honesty" },
  { text: "What's something I do that communicates love to you that I probably don't know I'm doing?", vibe: "deep", category: "Unfiltered Honesty" },
  { text: "What's something you wish you'd said to me earlier in our relationship that you can say now?", vibe: "deep", category: "Unfiltered Honesty" },
  { text: "Is there a part of yourself you've been showing me more of lately — and have you noticed that I've noticed?", vibe: "deep", category: "Unfiltered Honesty" },
  { text: "What's the thing about me you'd miss most if it changed?", vibe: "deep", category: "Unfiltered Honesty" },
  { text: "What's a moment from our relationship that you've replayed more than you've ever told me?", vibe: "deep", category: "Unfiltered Honesty" },
  { text: "What's something about the way I love you that surprised you — that you didn't know you needed?", vibe: "deep", category: "Unfiltered Honesty" },

  // SPICY
  { text: "What's something I do without thinking about it that you find genuinely attractive?", vibe: "spicy", category: "Attraction & Desire" },
  { text: "What's a version of me — different haircut, different outfit, different vibe — that you think you'd also be completely obsessed with?", vibe: "spicy", category: "Attraction & Desire" },
  { text: "What's the last thing I said or did that made you think about me in a not-totally-innocent way?", vibe: "spicy", category: "Attraction & Desire" },
  { text: "When do you feel most attracted to me — like a specific moment, time of day, or situation?", vibe: "spicy", category: "Attraction & Desire" },
  { text: "What's something you've wanted to try with me that you've been a little shy to bring up?", vibe: "spicy", category: "Attraction & Desire" },
  { text: "What's a compliment you've thought about giving me but kept to yourself?", vibe: "spicy", category: "Attraction & Desire" },
  { text: "What do you think I find most attractive about you — and is that what you'd want the answer to be?", vibe: "spicy", category: "Attraction & Desire" },
  { text: "What's something in a movie or show that made you think 'I want that with us'?", vibe: "spicy", category: "Attraction & Desire" },
  { text: "What's a spontaneous thing I could do that would completely disarm you?", vibe: "spicy", category: "Attraction & Desire" },
  { text: "What do you think is the most underrated thing about being with me?", vibe: "spicy", category: "Attraction & Desire" },

  { text: "What's a small, specific thing I do that you find more attractive than makes any logical sense?", vibe: "spicy", category: "Tension & Wanting" },
  { text: "What's a moment in our relationship where you felt a version of wanting me that surprised even you?", vibe: "spicy", category: "Tension & Wanting" },
  { text: "Is there a look I give you that you'd be embarrassed to explain to someone else?", vibe: "spicy", category: "Tension & Wanting" },
  { text: "What's something I could wear, say, or do that would completely short-circuit your brain?", vibe: "spicy", category: "Tension & Wanting" },
  { text: "What's a moment you've wanted to just stop talking and kiss me but didn't?", vibe: "spicy", category: "Tension & Wanting" },
  { text: "What's the most attracted you've ever been to me that had nothing to do with how I looked?", vibe: "spicy", category: "Tension & Wanting" },
  { text: "What's a setting or scenario that makes me more attractive to you — like a specific context where you just think 'yeah'?", vibe: "spicy", category: "Tension & Wanting" },
  { text: "What would a perfect night that ends exactly the way you want it to look like?", vibe: "spicy", category: "Tension & Wanting" },
  { text: "What do you think the most underrated thing about being physically close to me is?", vibe: "spicy", category: "Tension & Wanting" },
  { text: "If you had to pick one word to describe how it feels to be wanted by me, what would it be?", vibe: "spicy", category: "Tension & Wanting" },

  { text: "Would you rather I surprise you with a weekend trip I planned entirely myself, or let you plan it and pretend to be surprised?", vibe: "spicy", category: "Spicy Would You Rather" },
  { text: "Would you rather we try something totally new together once a month, or get really, really good at one thing we already love?", vibe: "spicy", category: "Spicy Would You Rather" },
  { text: "Would you rather I be more spontaneous and unpredictable, or more intentional and planned — when it comes to romance?", vibe: "spicy", category: "Spicy Would You Rather" },
  { text: "Would you rather have a whole evening with no phones, good food, and nowhere to be — or a completely unplanned night where anything could happen?", vibe: "spicy", category: "Spicy Would You Rather" },
  { text: "Would you rather I write you a letter about how I feel about you, or just show you right now?", vibe: "spicy", category: "Spicy Would You Rather" },
  { text: "Would you rather have more slow, deliberate moments together, or more wild, spontaneous ones?", vibe: "spicy", category: "Spicy Would You Rather" },
  { text: "Would you rather know exactly what I'm thinking right now, or have me tell you at the end of the night?", vibe: "spicy", category: "Spicy Would You Rather" },
  { text: "Would you rather be told something I've never said out loud, or shown something I've never done before?", vibe: "spicy", category: "Spicy Would You Rather" },
  { text: "Would you rather plan a date that's purely for me, or let me take over and plan something entirely for you?", vibe: "spicy", category: "Spicy Would You Rather" },
  { text: "Would you rather I be completely honest about one thing I've never told you, or let one mystery stay a mystery forever?", vibe: "spicy", category: "Spicy Would You Rather" },

  { text: "What's something about our relationship that you've never put into words but has been sitting in your chest?", vibe: "spicy", category: "Late Night Honest" },
  { text: "When's the last time I made you feel genuinely seen, and did I even know I was doing it?", vibe: "spicy", category: "Late Night Honest" },
  { text: "What's something you've forgiven me for that you never actually told me you forgave me for?", vibe: "spicy", category: "Late Night Honest" },
  { text: "What's a version of our future that scares you a little — not because it's bad, but because it matters?", vibe: "spicy", category: "Late Night Honest" },
  { text: "What's something I do that communicates love to you that I probably don't know I'm doing?", vibe: "spicy", category: "Late Night Honest" },
  { text: "What's something you wish you'd said to me earlier in our relationship that you can say now?", vibe: "spicy", category: "Late Night Honest" },
  { text: "Is there a part of yourself you've been showing me more of lately — and have you noticed that I've noticed?", vibe: "spicy", category: "Late Night Honest" },
  { text: "What's the thing about me you'd miss most if it changed?", vibe: "spicy", category: "Late Night Honest" },
  { text: "What's a moment from our relationship that you've replayed more than you've ever told me?", vibe: "spicy", category: "Late Night Honest" },
  { text: "What's something about the way I love you that surprised you — that you didn't know you needed?", vibe: "spicy", category: "Late Night Honest" },
]

export default questions